name: Build Docker Containers

on:
  push:
    branches: [ "master" ]
    paths:
      - 'bash-notebook/Dockerfile'

jobs:
  build-bash-notebook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Bash Jupyter Notebook
      run: docker build bash-notebook --file bash-notebook/Dockerfile --tag neshkeev/bash-notebook
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push bash-notebook to Docker Hub
      run: docker push neshkeev/bash-notebook:latest
